0 0 dataAuditErrors
263 0 4.1A.a/b, 4.1B: Active width >= 0.24um.
267 0 4.1C.a/b: Active spacing >= 0.28um.
277 0 4.1D.a: Nwell to N+ spacing >= 0.43um (1.8V).
284 0 4.1D.b: Nwell to N+ spacing >= 1.00um (3.3V).
293 0 4.1E: Nwell overlap N-tap >= 0.24um.
300 0 4.1F: Nwell to P-tap spacing >= 0.24um.
307 0 4.1G.a: Nwell overlap P+ Diffusion >= 0.43um (1.8V).
310 0 4.1G.b: Nwell overlap P+ Diffusion >= 1.00um (3.3V).
312 0 4A.1E/1F/1G Warning : Diffusion straddle N-Well
314 0 4.1H.a: Twell overlap N+ Diffusion >= 0.43um (1.8V).
317 0 4.1H.b: Twell overlap N+ Diffusion >= 1.00um (3.3V).
319 0 4.1I: Twell spacing N-tap in N-Well >= 0.24um.
322 0 4.1J: Twell overlap P-tap >= 0.24um.
324 0 4.1K.a: Twell to P+ spacing >= 0.43um (1.8V).
326 0 4.1K.b: Twell to P+ spacing >= 1.00um (3.3V).
328 0 4.1N: Minimum DIFFUSION area is 0.1936 um.sq
342 0 welnotr_StampErrorFloat
343 0 welnotr_StampErrorMult
344 0 welnotr_StampErrorConnect
349 0 nwel3_StampErrorFloat
350 0 nwel3_StampErrorMult
351 0 nwel3_StampErrorConnect
360 0 4.2A.a: Minimum N-Well width is 0.9um
364 0 4.2A.b: Minimum width for N-Well resistor is 1.5um
366 0 4.2A.c Maximum width for N-Well resistor is 20um
371 0 4.2B.a: Minimum Equal Potential N-Well spacing is 0um or >= 0.9um
373 0 4.2B.b1: Minimum Non-Equal Potential 1.8V N-Well spacing is 1.5um
375 0 4.2B.b2: Minimum N-Well to N-Well spacing (non-equal-potential, 3.3V device) is 2um.
377 0 4.2B.c: Minimum N-Well resistor spacing is 2.2um
378 0 4.2C: N-Well Resistor overlap N-well is 0um.
380 0 4.2D: N-Well Resistor to N+ Diffusion (for N-Well tap) is 0um.
391 0 4.2C/D: The resistor marker layer edges must either be entirely coincident       with N-Well edge or at least partially butted to N+ Tap (terminal).
396 0 4.3A: Minimum T-Well width is 0.9um
401 0 4.3B.a: Minimum Equal Potential T-Well spacing is 0um or >= 0.9um
408 0 4.3B.b1: Minimum Non-Equal Potential 1.8V T-Well spacing is 1.5um
415 0 4.3B.b2: Minimum Non-Equal Potential 3.3V T-Well spacing is 2.0um
420 0 4.3C: Minimum N-Well overlap T-Well is 1.5um
421 0 4.3C: T-Well must be surrounded by N-Well.
427 0 4.4A: Minimum Poly width for PMOS is 0.24um
431 0 4.4B: Minimum VTPL width is 0.45um
433 0 4.4C: Minimum VTPL spacing is 0.45um
436 0 4.4D: Minimum VTPL overlap Diffusion on the diffusion of related device is 0.3um
438 0 4.4E: Minimum VTPL to unrelated Diffusion spacing is 0.3um
441 0 4.4F: Minimum VTPL overlap Poly of related device is 0.4um
443 0 4.4G: Minimum VTPL to unrelated Poly spacing (in diffusion region) is 0.4um
453 0 4.5A: Minimum Poly width for PMOS is 0.5um
458 0 4.5B: Minimum VTPHL width is 0.45um
460 0 4.5C: Minimum VTPHL spacing is 0.45um
463 0 4.5D: Minimum VTPHL overlap Diffusion on the diffusion of related device is 0.3um
465 0 4.5E: Minimum VTPHL to unrelated Diffusion spacing is 0.3um
468 0 4.5F: Minimum VTPHL overlap Poly of related device is 0.4um
470 0 4.5G: Minimum VTPHL to unrelated Poly spacing (in diffusion region) >= 0.4um
475 0  4.6A: Minimum spacing of N_WELL to P_WELL_BLOCK is 0.9um.
484 0 4.7A.a: Minimum Poly width for NMOS (1.8V device) is 0.24um
485 0 4.7A.b: Minimum Poly width for NMOS (3.3V device) is 0.5um
489 0 4.7B: Minimum VTNL width is 0.45um
491 0 4.7C: Minimum VTNL spacing is 0.3um
494 0 4.7D: Minimum VTNL overlap Diffusion on the diffusion of related device is 0.3um
496 0 4.7E: Minimum VTNL to unrelated Diffusion spacing is 0.3um
499 0 4.7F: Minimum VTNL overlap Poly of related device is 0.4um
501 0 4.7G: Minimum VTNL to unrelated Poly spacing (in diffusion region) is 0.4um
509 0 4.8A: Minimum Poly width for NMOS is 0.3um
513 0 4.8B: Minimum VTNI width is 0.45um
515 0 4.8C: Minimum VTNI spacing is 0.45um
518 0 4.8D: Minimum VTNI overlap Diffusion on the diffusion of related device is 0.3um
520 0 4.8E: Minimum VTNI to unrelated Diffusion spacing is 0.3um
523 0 4.8F: Minimum VTNI overlap Poly of related device is 0.4um
525 0 4.8G: Minimum VTNI to unrelated Poly spacing (in diffusion region) is 0.4um
535 0 4.9A: Minimum Poly width for NMOS is 0.5um
540 0 4.9B: Minimum VTNHL width is 0.45um
542 0 4.9C: Minimum VTNHL spacing is 0.45um
545 0 4.9D: Minimum VTNHL overlap Diffusion on the diffusion of related device is 0.3um
547 0 4.9E: Minimum VTNHL to unrelated Diffusion spacing is 0.3um
550 0 4.9F: Minimum VTNHL overlap Poly of related device is 0.4um
552 0 4.9G: Minimum VTNHL to unrelated Poly spacing is 0.4um
558 0 4.13A: Minimum TG width is 0.45um
562 0 4.13B: Minimum TG spacing is 0.45um
568 0 4.13C: Minimum TG overlap Diffusion on the diffusion of 3.3V device is 0.3um
572 0 4.13D: Minimum TG to unrelated Diffusion spacing is 0.3um
585 0 4.13E: Minimum TG overlap Poly of 3.3V device is 0.4um
598 0 4.13F: Minimum TG to unrelated Poly spacing is 0.4um
605 0 4.14A/B/C: Minimum  Poly width is 0.18um.
608 0 4.14A.b: Minimum Poly width for NMOS (3.3V device) is 0.34um
611 0 4.14B.b: Minimum Poly width for PMOS (3.3V device) is 0.34um
641 0 4.14D.a1: Minimum Poly to Poly spacing (on diffusion region without contact in the spacing, Poly width <= 0.24um) is 0.28um.
645 0 4.14D.a2: Minimum Poly to Poly spacing (on difffusion region without contact in the spacing, Poly width > 0.24um(either side)) is 0.32um.
650 0 4.14D.b1/b2: Gate Poly spacing over diffusion w/contact is 0.34um
656 0 4.14D.c: Field Poly spacing is 0.24um
676 0 4.14D.c2.2: Wide Long Field Poly (width > 0.24um, length > 1.00um) spacing is 0.28um
680 0 4.14E: Minimum Poly extension onto field region (end cap) is 0.22um
692 0 4.14F: Minimum Poly on field region to Diffusion spacing is 0.1um
706 0 4.14G: Minimum end cap Poly to related Diffusion spacing is 0.12um
724 0 4.14H: Minimum Poly gate to field edge spacing is 0.28um
730 0 4.14I.a: 1.8V bent gate width >= 0.20um.
736 0 4.14I.b: Minimum Poly width for 45 degree bent gate is 0.38um
750 0 4.14J: Poly 90 degree bent gate is not allowed.
752 0 4.14K: Maximum Poly overlap Diffusion area is 6400 um^2
765 0 4.14N: Minimum Poly bent gate on field region to Diffusion spacing is 0.2um
767 0 4.14O: Minimum POLY1 area is 0.198 um.sq
784 0 4.15A: Minimum HR width is 0.6um
786 0 4.15B: Minimum HR to HR spacing is 0.6um
788 0 4.15C: Minimum HR Poly width is 0.18um
790 0 4.15D: Minimum SAB width for HR Poly resistor (Defome HR Poly resistor length) is 1.0um
794 0 4.15E: Minimum HR mask overlap HR Poly resistor is 1.5um
797 0 4.15F: Minimum HR to unrelated Poly spacing is 2.0um
799 0 4.15G: Minimum N+imp layer to HR Poly spacing is 0.5um
802 0 4.15H: Minimum P+imp layer to HR Poly spacing is 0.5um
813 0 4.15I: Minimum SAB extension over HR Poly is 0.5um
815 0 4.15J: Minimum HR Poly contact to SAB spacing is 0.5um
816 0 4.15K: Minimum HR to unrelated diffusion spacing is 0.5um
818 0 4.15L: Minimum NWELL layer overlap HR Poly is 2.0um
819 0 4.15M: HR Poly resistor must be allocated inside N-Well.
825 0 4.15N: P+ implant overlap SAB is 0.2um
827 0 4.15O: Minimum P+ implant spacing to unrelated poly resistor is 0.4um
830 0 4.15P: Minimum P+ implant layer overlap HR poly is 0.3um (this is the same for non-salicide poly resistor)
832 0 Warning : Active without N+ or P+ implant overlap was found
839 0 4.16A: Minimum N+ implant width is 0.40um.
844 0 4.16B: Minimum N+ implant spacing is 0.40um.
855 0 4.16C.a: Minimum N+ implant overlap N+ Diffusion (inside P-Well or Twell) is 0.22um
859 0 4.16C.b: Minimum N+ implant overlap N+ Diffusion (inside N-Well) is 0.08um
863 0 4.16D.a: Minimum N+ implant to P+ Diffusion (inside N-Well) spacing is 0.22um
870 0 4.16D.b: Minimum N+ implant to P+ Diffusion (inside P-Well or Twell) spacing is 0.08um
872 0 4.17J/4.16J: Minimum N+/P+ implant extension over Poly to form N+/P+ S/D is 0.32um
874 0 4.16F/4.17F: Minimum N+ to P+ diffusion spacing in the same potential is 0um
877 0 4.16F,M/4.17F,M: Butting N+ to P+ Diffusions must be at the same potential (electrically connected).
880 0 4.16G/4.17H: Minimum N+ implant overlap Diffusion / Diffusion extension over P+ implant to form N+ region is 0.24um
882 0 4.17G/4.16H: Minimum P+ implant overlap Diffusion / Diffusion extension over N+ Implant to form P+ region is 0.24um
885 0 4.16I/4.17J: Minimum N+ implant to Poly spacing / P+ implant extension over Poly to form P+ S/D region is 0.32um
887 0 4.17I/4.16J: Minimum P+ implant to Poly spacing / N+ implant extension over Poly to form N+ S/D region is 0.32um
891 0 4.16K/4.17L: Minimum N+ implant overlap N+ contact / P+ implant to N+ contact spacing is 0.12um
907 0 4.16N: Maximum N+ Diffusion to the nearest P+ pick-up spacing (inside P-Well or Twell) is 20um (I/O, RAM, ROM, capacitor and diode are excepted)
908 0 4.16O: Minimum NPLUS area is 0.2916 sq.um
911 0 4.16P: Minimum NPLUS enclosed area 0.2916sq.um
918 0 4.17A: Minimum P+ implant width is 0.4um
923 0 4.17B: Minimum P+ implant spacing is 0.4um
927 0 4.17C.a: Minimum P+ implant overlap P+ Diffusion (inside N-Well) is 0.22um
937 0 4.17C.b: Minimum P+ implant overlap P+ Diffusion (inside P-Well or Twell) is 0.08um
944 0 4.17D.a: Minimum P+ implant to N+ Diffusion (inside P-Well or Twell) spacing is 0.22um
945 0 4.17D.b: Minimum P+ implant to N+ Diffusion (inside N-Well) spacing is 0.08um
950 0 4.16L/4.17K: Minimum P+ implant overlap P+ contact / Minimum N+ implant to P+ contact spacing is 0.12um
960 0 4.16M/17M: Soft Contacts are prohibited.
992 0 4.17N: Maximum P+ Diffusion to the nearest N+ pick-up spacing is 20um (I/O, RAM, ROM, capacitor and diode are excepted)
993 0 4.17O: Minimum PPLUS area is 0.2916 sq.um
996 0 4.17P: Minimum PPLUS enclosed area 0.2916sq.um
1014 0 4.18A: Minimum SAB width is 0.6um
1018 0 4.18B: Minimum SAB spacing is 0.6um
1019 0 4.18C: Non-salicide contact is not allowed.
1022 0 4.18E: Minimum SAB overhang of Diffusion is 0.3um
1025 0 4.18F: Minimum Diffusion overhang of SAB is 0.3um.
1029 0 4.18G.a: Minimum SAB to Diffusion Contact spacing is 0.3um
1035 0 4.18G.b: Minimum SAB to Poly Contact spacing is 0.3um
1037 0 4.18H: Minimum SAB to unrelated Diffusion spacing is 0.24um
1039 0 4.18.I.b: Minimum SAB to Poly Contact spacing is 0.3um.
1054 0 4.18K: Minimum SAB extension over Diffusion non-salicide resistor is 0.38um
1060 0 4.18L: Minimum SAB extension over Poly non-salicide resistor is 0.38um
1071 0 4.18M: Minimum SAB to salicide contact spacing is 0.38um (include 4.18F.b)
1076 0 4.18N: Minimum P+ implant layer overlap P+ Poly non-salicide resistor is 0.3um
1078 0 4.18O: Minimum P+ implant layer to N+ Poly non-salicide resistor spacing is 0.3um
1083 0 4.18P: P+ Poly non-salicide resistor must be allocated inside N-Well. Minimum N-Well overlap P+ Poly non-salicide resistor is 0.3um
1087 0 4.18Q: N+ Poly non-salicide resistor must be allocated outside N-Well. Minimum N-Well to N+ Poly non-salicide resistor spacing is 0.3um
1092 0 4.18R: Minimum N+ implant layer overlap N+ Poly non-salicide resistor is 0.3um
1094 0 4.18S: Minimum N+ implant layer to P+ Poly non-salicide resistor spacing is 0.3um
1095 0 4.18T: Non-salicide contact for device or non-salicide resistor is not allowed.
1159 0 4.18.Y1.a: Minimum N+ implant enclosure of (N+ POLY1 OVER SAB) is 0.20 um,  (POLY1 endcap is excepted from this rule)
1171 0 4.18.Y1.b: If SAB lies across POLY1,(POLY1 OVER SAB) partially covered,  by N+ and partially not covered by N+ is not allowed
1182 0 4.18.Y2.a: Minimum P+ implant enclosure of ((P+ POLY1 OVER SAB) NOT HR) is 0.20 um,  (POLY1 endcap is excepted from this rule)
1194 0 4.18.Y2.b: If SAB lies across POLY1,((POLY1 OVER SAB) NOT HR) partially covered,  by P+ and partially not covered by P+ is not allowed
1201 0 4.18.Y3.a: Minimum N+ implant enclosure of (N+ DIFFUSION OVER SAB) is 0.20 um,  (DIFFUSION endcap is excepted from this rule)
1208 0 4.18.Y3.b: (DIFFUSION OVER SAB) partially covered by N+ and partially not covered by N+ is not allowed
1215 0 4.18.Y4.a: Minimum P+ implant enclosure of (P+ DIFFUSION OVER SAB) is 0.20 um,  (DIFFUSION endcap is excepted from this rule)
1222 0 4.18.Y4: (DIFFUSION OVER SAB) partially covered by P+ and partially not covered by P+ is not allowed
1227 0 4.19A: Maximum and Minimum Contact size is 0.24 X 0.24um^2
1236 0 4.19B: Minimum Contact spacing is 0.26um
1245 0 4.19C.a: Minimum Diffusion Contact to Poly spacing (1.8V device) is 0.15um
1250 0 4.19C.b: Minimum Diffusion Contact to Poly spacing (3.3 device) is 0.3um
1257 0 4.19D: Minimum Poly Contact to Diffusion edge spacing is 0.18um
1270 0 4.19E: Minimum Poly overlap Contact is 0.1um
1281 0 4.19F: P+ Diffusion overlap Contact is 0.1um
1292 0 4.19G: N+ Diffusion overlap Contact is 0.1um
1294 0 4.19I: Poly contact on Diffusion is not allowed.
1301 0 4.20A: Minimum Metal1 width is 0.24um
1307 0 4.20B.a: Minimum Metal1 to Metal1 spacing (absolute minimum) is 0.24um
1317 0 4.20B.b: Minimum Metal1 to Metal1 spacing (for Metal1 width >= 10um) is 0.28um
1319 0 4.20D.a/d: Minimum Metal1 overlap contact is 0um
1330 0 4.20D.b/c/e: Minimum Metal1 must enclose the contact on two entire non-adjacent edges is 0.08um
1332 0 4.20E: Minimum Metal1 area is 0.1764 um^2
1335 0 4.21A: Maximum and Minimum Mvia1 size is 0.28 X 0.28um^2
1343 0 4.21B.a/b: Minimum Mvia1 to Mvia1 spacing is 0.28um
1344 0 4.21C.a: Minimum Metal1 overlap Mvia1 is 0um
1357 0 4.21C.b: Minimum wide Metal1 (>= 10.00um) overlap Mvia1 is 0.2um
1365 0 4.21C.c/d/e: Minimum Metal1 must enclose the Mvia1 on two entire non-adjacent edges is 0.08um
1371 0 4.22A: Minimum Metal2 width is 0.28um
1375 0 4.22B: Minimum Metal2 to Metal2 spacing (absolute minimum) is 0.28um
1385 0 4.22B.b: Minimum Metal2 to Metal2 spacing (for Metal2 width >= 10um) is 0.32um
1386 0 4.22D.a/d: Minimum Metal2 overlap Mvia1 is 0um
1392 0 4.22D.b/c/e: Minimum Metal2 must enclose the Mvia1 on two entire non-adjacent edges is 0.08um
1394 0 4.22E: Minimum Metal2 area is 0.1936 um^2
1397 0 4.23A: Maximum and Minimum Mvia2 size is 0.28 X 0.28um^2
1399 0 4.23B.a/b: Minimum Mvia2 to Mvia2 spacing is 0.28um
1400 0 4.23C.a: Minimum Metal2 overlap Mvia2 is 0um
1413 0 4.23C.b: Minimum wide Metal2 (>= 10.00um) overlap Mvia2 is 0.20um
1419 0 4.23C.c/d/e: Minimum Metal2 must enclose the Mvia2 on two entire non-adjacent edges is 0.08um
1423 0 4.24A: Minimum Metal3 width is 0.28um
1425 0 4.24B: Minimum Metal3 to Metal3 spacing (absolute minimum) is 0.28um
1435 0 4.24B.b: Minimum Metal3 to Metal3 spacing (for Metal3 width >= 10um) is 0.32um
1436 0 4.24D.a/d: Minimum Metal3 overlap Mvia2 >= 0um
1442 0 4.24D.b/c/e: Minimum Metal3 must enclose the Via2 on two entire non-adjacent edges is 0.08um
1444 0 4.24E: Minimum Metal3 area is 0.1936 um^2
1447 0 4.25A: Maximum and Minimum Mvia3 size is 0.28 X 0.28um^2
1449 0 4.25B.a/b: Minimum Mvia3 to Mvia3 spacing is 0.28um
1450 0 4.25C.a: Minimum Metal3 overlap Mvia3 is 0um
1463 0 4.25C.b: Minimum wide Metal3 (>= 10.00um) Overlap Mvia3 is 0.2um
1469 0 4.25C.c/d/e: Minimum Metal3 must enclose the Via3 on two entire non-adjacent edges is 0.08um
1473 0 4.26A: Minimum Metal4 width is 0.28um
1475 0 4.26B: Minimum Metal4 to Metal4 spacing (absolute minimum) is 0.28um
1485 0 4.26B.b: Minimum Metal4 to Metal4 spacing (for Metal4 width >= 10um) is 0.32um
1486 0 4.26D.a/d: Minimum Metal4 overlap Mvia3 is 0um
1492 0 4.26D.b/c/e: Minimum Metal4 must enclose the Via3 on two entire non-adjacent edges is 0.08um
1494 0 4.26E: Minimum Metal4 area is 0.1936 um^2
1497 0 4.27A: Maximum and Minimum Mvia4 size is 0.28 X 0.28um^2
1499 0 4.27B.a/b: Minimum Mvia4 to Mvia4 spacing is 0.28um
1500 0 4.27C.a: Minimum Metal4 overlap Mvia4 is 0um
1513 0 4.27C.b: Minimum wide Metal4 (>= 10um) Overlap Mvia4 is 0.2um
1519 0 4.27C.c/d/e: Minimum Metal4 must enclose the Via4 on two entire non-adjacent edges is 0.08um
1525 0 4.28A: Minimum Metal5 width is 0.28um
1527 0 4.28B: Minimum Metal5 to Metal5 spacing (absolute minimum) is 0.28um
1537 0 4.28B.b: Minimum Metal5 to Metal5 spacing (for Metal5 width >= 10um) is 0.32um
1538 0 4.28D.a/d: Minimum Metal5 overlap Mvia4 is 0um
1544 0 4.28D.b/c/e: Minimum Metal5 must enclose the Via4 on two entire non-adjacent edges is 0.08um
1546 0 4.28E: Minimum Metal5 area is 0.1936 um^2
1549 0 4.30A: Maximum and Minimum Mvia5 size is 0.28 X 0.28um^2
1551 0 4.30B.a/b: Minimum Mvia5 to Mvia5 spacing is 0.28um
1552 0 4.30C.a: Minimum Metal5 overlap MVia5 is 0um
1565 0 4.30C.b: Minimum wide Metal5 (>= 10um) Overlap MVia5 is 0.2um
1568 0 4.30C.c/d/e: Minimum Metal5 must enclose the Via5 on two entire non-adjacent edges is 0.08um
1575 0 4.29A: Minimum METAL_CAP width is 0.6um
1577 0 4.29B: Minimum METAL_CAP to METAL_CAP spacing is 0.55um
1583 0 4.29C: Minimum LSM overlap METAL_CAP Length is 0.5um
1585 0 4.29C: METAL_CAP layer must be within LSM area.
1588 0 4.29D: Minimum METAL_CAP overlap LMvia Length is 0.5um
1589 0 4.29D: METAL_CAP must overlap LMvia - straddle is not allowed.
1591 0 4.29E: Minimum Unrelated LMvia to METAL_CAP spacing is 0.5um
1593 0 4.29F: Maximum METAL_CAP overlap LSM area = 100um*100um.
1601 0 4.29G: The minimum overlap of M1 ground plate to LSM is 10um
1605 0 4.29H: Minimum overlap of P-Well block layer (block P-Well implant) to LSM is 10um
1606 0 4.29I:Outside MCAP : Minimum spacing of diffusion to MCAP is 1um
1609 0 4.29I_b: Inside MCAP : Minimum MCAP enclosure of DIFFUSION is 4um
1611 0 4.29I_c: Inside MCAP :  Minimum spacing of DIFFUSION to LSM is 4um
1612 0 4.29J: Minimum spacing of N_WELL to MCAP is 0um
1613 0 4.29K: Minimum spacing of POLY1 to MCAP is 0um
1614 0 4.29L: Minimum spacing of N+ to MCAP is 0um
1618 0 4.31A: Minimum Thick Top Metal width is 0.8um
1620 0 4.31B: Minimum Thick Top Metal to Top Metal spacing (absolute minimum) is 0.8um
1632 0 4.31B.b: Minimum Thick Top Metal to Top Metal spacing (for Top Metal width >= 10um) is 1.2um
1638 0 4.31C: Minimum Top Via must be enclosed by Thick Top Metal is 0.2um
1640 0 4.31D: Minimum Top Metal area is 2.56 um^2
1649 0 4.31H: The minimum overlap of IND to inductor layer is 10um
1654 0 4.31H: The minimum overlap of IND to inductor layer is 10um
1659 0 4.33A: Minimum PESD width is 0.6um
1661 0 4.33B: Minimum PESD spacing is 0.60um
1678 0 drc(DIFF (width < 0.14))
1682 0 drc(DIFF (width < 0.01) withCornerTouch fig)
1687 0 drc(DIFF (sep < 0.26))
1692 0 drc(DIFF (notch < 0.11))
1697 0 drc(NWEL ndiff1_ram (sep < 0.38))
1703 0 drc(NWEL pdiff1_ram (enc < 0.2))
1707 0 drc(PO1 (width < 0.08))
1711 0 drc(PO1 (width < 0.01) withCornerTouch fig)
1721 0 BDSP4.8D.b
1727 0 BDSP_4.8D.c1_1
1733 0 BDSP_4.8D.c1_2
1738 0 drc(blfpedg ((0 < sep) < 0.24))
1743 0 drc(blfpedg smfpedg ((0 < sep) < 0.24))
1749 0 drc(PO1 DIFF (enc < 0.01))
1752 0 BDSP4.8F
1758 0 BDSP_4.8G
1762 0 BDSP_4.8H
1764 0 BDSP_4.8J
1769 0 drc(bent_fpoly gate_diff_edge (sep < 0.02))
1775 0 drc(bent_fpoly gate_diff_edge (enc < 0.02))
1779 0 BDSP_4.17D.b
1784 0 drc(ctdiff1 PO1 (sep < 0.08))
1789 0 drc(ctfpol DIFF (sep < 0.17))
1795 0 drc(pact ctpdiff (enc < 0.03))
1801 0 drc(nact ctndiff (enc < 0.03))
1806 0 drc(ME1 (sepNotch < 0.23))
1814 0 BDSP_4.13D.bc
1819 0 BDSP_4.14C.c/d/e
1823 0 drc(DIFF (width < 0.07))
1827 0 drc(DIFF (width < 0.01) withCornerTouch fig)
1832 0 drc(DIFF (sep < 0.26))
1837 0 drc(DIFF (notch < 0.11))
1842 0 drc(NWEL ndiff1_ram (sep < 0.38))
1847 0 BLSP_4.1E
1853 0 drc(NWEL pdiff1_ram (enc < 0.2))
1857 0 drc(PO1 (width < 0.09))
1861 0 drc(PO1 (width < 0.01) withCornerTouch fig)
1866 0 BLSP_4.8D.a1
1871 0 BLSP_4.8D.a2
1877 0 BLSP_4.8D.b1
1884 0 BLSP_4.8D.c1_1
1891 0 BLSP_4.8D.c1_2
1899 0 BLSP_4.8D.c22
1905 0 drc(PO1 DIFF (enc < 0.02))
1910 0 BLSP_4.8G
1914 0 BLSP_4.8H
1922 0 BLSP_4.8N: Minimum bent field Poly to Diffusion spacing is 0.05um
1928 0 drc(NPLUS actpsub (enc < 0.15))
1933 0 drc(NPLUS actnwel (sep < 0.19))
1938 0 BLSP_4.10D.b
1942 0 drc(CONT (width < 0.05))
1946 0 drc(CONT (width < 0.01) withCornerTouch fig)
1951 0 drc(CONT (sep < 0.22))
1956 0 drc(CONT (notch < 0.1))
1962 0 drc(PO1 polcnt (enc < 0.031))
1966 0 drc(ME1 (width < 0.05))
1971 0 drc(ME1 (sepNotch < 0.16))
1975 0 drc(DIFF (width < 0.07))
1980 0 drc(DIFF (sep < 0.26))
1985 0 drc(DIFF (notch < 0.11))
1990 0 drc(NWEL ndiff1_ram (sep < 0.38))
1996 0 drc(NWEL pdiff1_ram (enc < 0.2))
2000 0 drc(PO1 (width < 0.09))
2006 0 BLSP1_4.8D.a1
2011 0 BLSP1_4.8D.a2
2015 0 BLSP1_4.8D.b1
2021 0 BLSP1_4.8D.c1_1
2027 0 BLSP1_4.8D.c1_2
2035 0 BLSP1_4.8D.c22
2043 0 BLSP1_4.8D.c22
2047 0 BLSP1_4.8E
2052 0 BLSP1_4.8F
2057 0 BLSP1_4.8G
2063 0 drc(DIFF gate ((0 < enc) < 0.02))
2068 0 drc(bent_fpoly gate_diff_edge (sep < 0.05))
2074 0 drc(bent_fpoly gate_diff_edge (enc < 0.05))
2080 0 drc(NPLUS actpsub (enc < 0.19))
2084 0 drc(CONT (width < 0.05))
2089 0 drc(CONT (sep < 0.22))
2094 0 drc(CONT (notch < 0.1))
2100 0 drc(PO1 ctfpol (enc < 0.05))
2106 0 drc(pact ctpdiff (enc < 0.01))
2112 0 drc(nact ctndiff (enc < 0.01))
2116 0 drc(ME1 (width < 0.05))
2121 0 drc(ME1 (sepNotch < 0.15))
2126 0 BLSP1_4.13D
2131 0 drc(NWEL ndiff1_ram (sep < 0.43))
2137 0 drc(NWEL pdiff1_ram (enc < 0.32))
2140 0 DP_4.8F
2148 0 DP_4.8G
2152 0 DP_4.9C.a
2158 0 drc(NPLUS actnwel ((0 < enc) < 0.04))
2162 0 DP_4.9D.b
2168 0 drc(PPLUS actpsub ((0 < enc) < 0.07))
2173 0 drc(PPLUS actpsub ((0 < sep) < 0.22))
2178 0 DP_4.10D.b
2184 0 drc(PO1 ctfpol (enc < 0.08))
2190 0 drc(pact ctpdiff (enc < 0.07))
2196 0 drc(nact ctndiff (enc < 0.07))
2200 0 drc(ME1 (width < 0.07))
2205 0 drc(ME1 (sep < 0.21))
2210 0 drc(ME1 (notch < 0.2))
2220 0 DP_4.13D
2224 0 drc(DIFF (width < 0.14))
2229 0 drc(DIFF (sep < 0.26))
2234 0 drc(DIFF (notch < 0.11))
2239 0 drc(NWEL ndiff1_ram (sep < 0.33))
2245 0 drc(NWEL pdiff1_ram (enc < 0.36))
2249 0 drc(PO1 (width < 0.08))
2255 0 DP1_4.8D.b1
2261 0 DP1_4.8D.c1
2267 0 drc(PO1 DIFF (enc < 0.03))
2272 0 drc(PO1 DIFF (sep < 0.07))
2278 0 DP1_4.8G
2282 0 DP1_4.8H
2284 0 DP1_4.8J
2289 0 drc(ctdiff1 PO1 (sep < 0.06))
2295 0 drc(pact ctpdiff (enc < 0.03))
2301 0 drc(nact ctndiff (enc < 0.03))
2305 0 drc(DIFF (width < 0.14))
2310 0 drc(DIFF (sep < 0.26))
2315 0 drc(DIFF (notch < 0.11))
2320 0 drc(NWEL ndiff1_ram (sep < 0.38))
2326 0 drc(NWEL pdiff1_ram (enc < 0.2))
2330 0 drc(PO1 (width < 0.08))
2336 0 DP2_4.8D.b1
2342 0 DP2_4.8D.c1.1
2348 0 DP2_4.8D.c1.2
2354 0 drc(PO1 DIFF (enc < 0.01))
2359 0 drc(PO1 DIFF (sep < 0.02))
2365 0 DP2_4.8G
2370 0 DP2_4.8H
2372 0 DP2_4.8J
2377 0 drc(bent_fpoly gate_diff_edge (sep < 0.02))
2383 0 drc(bent_fpoly gate_diff_edge (enc < 0.02))
2388 0 drc(ctdiff1 PO1 (sep < 0.08))
2393 0 drc(ctfpol DIFF (sep < 0.17))
2399 0 drc(pact ctpdiff (enc < 0.03))
2405 0 drc(nact ctndiff (enc < 0.03))
2410 0 DP2_4.13D
2415 0 DP2_4.14C.b
2420 0 drc(ctdiff1 PO1 (sep < 0.14))
2426 0 drc(pact ctpdiff (enc < 0.09))
2432 0 drc(nact ctndiff (enc < 0.09))
2436 0 drc(DIFF (width < 0.07))
2441 0 drc(DIFF (sep < 0.26))
2446 0 drc(DIFF (notch < 0.11))
2451 0 drc(NWEL ndiff1_ram (sep < 0.38))
2457 0 drc(NWEL pdiff1_ram (enc < 0.2))
2461 0 drc(PO1 (width < 0.09))
2466 0 BLSPLP_4.14D.a1
2470 0 BLSPLP_4.14D.a2
2475 0 BLSPLP_4.14D.b1
2481 0 BLSPLP_4.14D.c1_1
2487 0 BLSPLP_4.14D.c1_2
2503 0 BLSPLP_4.14D.c2.1a
2511 0 BLSPLP_4.14G
2516 0 drc(bent_fpoly gate_diff_edge (sep < 0.05))
2520 0 drc(NPLUS (width < 0.29))
2525 0 drc(NPLUS (sepNotch < 0.234))
2531 0 drc(NPLUS actpsub (enc < 0.2))
2536 0 drc(PPLUS (sepNotch < 0.235))
2541 0 drc(CONT (sep < 0.22))
2546 0 drc(CONT (notch < 0.1))
2552 0 drc(pact ctpdiff (enc < 0.01))
2558 0 drc(nact ctndiff (enc < 0.01))
2562 0 drc(ME1 (width < 0.05))
2567 0 drc(ME1 (sep < 0.13))
2572 0 BLSPLP_4.21C.c/d/e
