0 0 dataAuditErrors
439 0  nsd/ptap butting issue: nsd/ptap need to be connected by metal and contact
440 0  psd/ntap butting issue: psd/ntap need to be connected by metal and contact
441 0 PTAP is wrongly connected to POWER ! 
442 0 NTAP is wrongly connected to GROUND ! 
444 0 psub_StampErrorFloat
445 0 psub_StampErrorMult
446 0 psub_StampErrorConnect
451 0 wel_StampErrorFloat
452 0 wel_StampErrorMult
453 0 wel_StampErrorConnect
458 0 TWEL_StampErrorFloat
459 0 TWEL_StampErrorMult
460 0 TWEL_StampErrorConnect
1594 0 malformed device ngate_sp
1595 0 malformed device pgate_sp
1596 0 malformed device hngate_sp
1597 0 malformed device hpgate_sp
1598 0 malformed device ng_sram
1599 0 malformed device RBNPG_B6T400
1600 0 malformed device RBNPD_B6T400
1601 0 malformed device RBPGAT_B6T400
1602 0 malformed device RBNPG_B8T1020
1603 0 malformed device RBNPD_B8T1020
1604 0 malformed device RBPGAT_B8T1020
1605 0 malformed device pg_sram
1606 0 malformed device welres
1607 0 malformed device sndres
1608 0 malformed device spdres
1609 0 malformed device snpyr
1610 0 malformed device sppyr
1611 0 malformed device nsndres
1612 0 malformed device nspdres
1613 0 malformed device nsnpyr
1614 0 malformed device nsppyr
1615 0 malformed device bjt_v5
1616 0 malformed device bjt_v10
1617 0 malformed device dioden
1618 0 malformed device diodep
1619 0 malformed device NWNACT
1620 0 malformed device ngate_mm
1621 0 malformed device pgate_mm
1622 0 malformed device nmos_cap
1623 0 malformed device pmos_cap
1624 0 malformed device hngate_mm
1625 0 malformed device hpgate_mm
1626 0 malformed device ngate_lvt
1627 0 malformed device pgate_lvt
1628 0 malformed device hngate_lvt
1629 0 malformed device hpgate_lvt
1630 0 malformed device ngate_zt
1631 0 malformed device hngate_zt
1632 0 malformed device ngate_bpw
1633 0 malformed device hngate_bpw
1634 0 malformed device nsnpyr_mm
1635 0 malformed device nsppyr_mm
1636 0 malformed device hrpyres_mm
1637 0 malformed device m1res
1638 0 malformed device m2res
1639 0 malformed device m3res
1640 0 malformed device m4res
1641 0 malformed device m5res
1642 0 malformed device m6res
1643 0 malformed device bjt_v5_mm
1644 0 malformed device bjt_v10_mm
1645 0 malformed device cmmc_mm
1646 0 malformed device dioden_mm
1647 0 malformed device diodep_mm
1648 0 malformed device NWNACT_MM
1649 0 malformed device ng_rf
1650 0 malformed device ng_srf
1651 0 malformed device pg_rf
1652 0 malformed device pg_srf
1653 0 malformed device hng_rf
1654 0 malformed device hng_srf
1655 0 malformed device hpg_rf
1656 0 malformed device hpg_srf
1657 0 malformed device nsnpyr_rf
1658 0 malformed device nsppyr_rf
1659 0 malformed device hrpyres_rf
1660 0 malformed device varmis_rf
1661 0 malformed device vard_rf
1662 0 malformed device cmmc_msq_rf
1663 0 malformed device rf_pad
1664 0 malformed device ind_me
1972 0 unstable device for ind_me_Device_1409
1973 0 unstable device for rf_pad_Device_1390
1974 0 unstable device for cmmc_msq_rf_Device_1364
1975 0 unstable device for vard_rf_Device_1350
1976 0 unstable device for varmis_rf_Device_1322
1977 0 unstable device for hrpyres_rf_Device_1299
1978 0 unstable device for nsppyr_rf_Device_1280
1979 0 unstable device for nsnpyr_rf_Device_1261
1980 0 unstable device for hpg_srf_Device_1235
1981 0 unstable device for hpg_rf_Device_1205
1982 0 unstable device for hng_srf_Device_1175
1983 0 unstable device for hng_rf_Device_1145
1984 0 unstable device for pg_srf_Device_1115
1985 0 unstable device for pg_rf_Device_1085
1986 0 unstable device for ng_srf_Device_1055
1987 0 unstable device for ng_rf_Device_1025
1988 0 unstable device for NWNACT_MM_DIODE_1014
1989 0 unstable device for diodep_mm_DIODE_1007
1990 0 unstable device for dioden_mm_DIODE_1000
1991 0 unstable device for cmmc_mm_Device_990
1992 0 unstable device for bjt_v10_mm_BJT_982
1993 0 unstable device for bjt_v5_mm_BJT_972
1994 0 unstable device for m6res_Device_960
1995 0 unstable device for m5res_Device_952
1996 0 unstable device for m4res_Device_944
1997 0 unstable device for m3res_Device_936
1998 0 unstable device for m2res_Device_928
1999 0 unstable device for m1res_Device_920
2000 0 unstable device for hrpyres_mm_Device_911
2001 0 unstable device for nsppyr_mm_Device_901
2002 0 unstable device for nsnpyr_mm_Device_891
2003 0 unstable device for hngate_bpw_MOS_882
2004 0 unstable device for ngate_bpw_MOS_871
2005 0 unstable device for hngate_zt_MOS_860
2006 0 unstable device for ngate_zt_MOS_849
2007 0 unstable device for hpgate_lvt_MOS_838
2008 0 unstable device for hngate_lvt_MOS_827
2009 0 unstable device for pgate_lvt_MOS_816
2010 0 unstable device for ngate_lvt_MOS_805
2011 0 unstable device for hpgate_mm_MOS_794
2012 0 unstable device for hngate_mm_MOS_783
2013 0 unstable device for pmos_cap_MOS_772
2014 0 unstable device for nmos_cap_MOS_761
2015 0 unstable device for pgate_mm_MOS_750
2016 0 unstable device for ngate_mm_MOS_739
2017 0 unstable device for NWNACT_DIODE_730
2018 0 unstable device for diodep_DIODE_723
2019 0 unstable device for dioden_DIODE_716
2020 0 unstable device for bjt_v10_BJT_708
2021 0 unstable device for bjt_v5_BJT_698
2022 0 unstable device for nsppyr_RES_686
2023 0 unstable device for nsnpyr_RES_678
2024 0 unstable device for nspdres_RES_670
2025 0 unstable device for nsndres_RES_662
2026 0 unstable device for sppyr_RES_654
2027 0 unstable device for snpyr_RES_646
2028 0 unstable device for spdres_RES_638
2029 0 unstable device for sndres_RES_630
2030 0 unstable device for welres_RES_622
2031 0 unstable device for pg_sram_MOS_615
2032 0 unstable device for RBPGAT_B8T1020_MOS_604
2033 0 unstable device for RBNPD_B8T1020_MOS_593
2034 0 unstable device for RBNPG_B8T1020_MOS_582
2035 0 unstable device for RBPGAT_B6T400_MOS_571
2036 0 unstable device for RBNPD_B6T400_MOS_560
2037 0 unstable device for RBNPG_B6T400_MOS_549
2038 0 unstable device for ng_sram_MOS_538
2039 0 unstable device for hpgate_sp_MOS_526
2040 0 unstable device for hngate_sp_MOS_514
2041 0 unstable device for pgate_sp_MOS_502
2042 0 unstable device for ngate_sp_MOS_490
